language: node_js
node_js:
- 0.1
before_deploy:
- gulp build-client
- zip -r revision *
- mkdir -p uploads
- mv revision.zip uploads/revision.zip
deploy:
  matrix:
  - provider: s3
    access_key_id: AKIAIKPGQSIBKZSYRAKQ
    secret_access_key:
      secure: Aj6brRjDuA/a+gKjAMBEgMhwAuC1boK23vMvJpqit3yOUpJXzbg8yPBfwQ+9sFW27ul9SrYKxCpOsW6QIGKlfzpKS2z2CmwrP8RxitPEBCUhHdy5FkMXLPbHWdRU9pg85lD/WQ+Ql6EzLyGmvgQ3CG6dmzexgfCVZMk3uxtMn6xysWAKDAlknA0LWetbTSyEVuwB98l3Yec93DGkpOaxetz+dZbOQzzrBPNja7xWJSEW6FDCoGbNj0rh77HCINHaSqDIrzsWc8D06oOcP1gTnoAaK3s49Yykp5SoJYtKaLjOy4yOUcXGkpnFvJCfzR5x7mlVwtDibZY31/yzLQMXrhD4rE/0iHcaEITsytl7CxweGyH/Q6FLJtALQW5UrI44mIWH7uW45iVCfz/kqatSdHONe82YRs7bgX46Biodj+eE7qdQTQq36ndd05pzljRauH/fhQhSVSijRYMieZ/S9To+pd9qozbXPFznZCiAYWc7evuBdNpJ1houAJIPhQkCfaBA+6iZR9321ZFsReL2O+bvoxyvDffqKGr/96q5CA14H+/7G9uZh50iRO+Wl73mb5gaiiZkOOsmU1FRkbYDzu93WmxskgwSoGdqiDhPmsowuSRttH5wV/HE4UkYybCgN0c9ARSO+ipYAz8o0zN6QNB+MoCK9gKiGkQFSUnmLtI=
    local_dir: uploads
    skip_cleanup: true
    bucket: twotek-revisions
  - provider: codedeploy
    access_key_id: AKIAIKPGQSIBKZSYRAKQ
    secret_access_key:
      secure: Aj6brRjDuA/a+gKjAMBEgMhwAuC1boK23vMvJpqit3yOUpJXzbg8yPBfwQ+9sFW27ul9SrYKxCpOsW6QIGKlfzpKS2z2CmwrP8RxitPEBCUhHdy5FkMXLPbHWdRU9pg85lD/WQ+Ql6EzLyGmvgQ3CG6dmzexgfCVZMk3uxtMn6xysWAKDAlknA0LWetbTSyEVuwB98l3Yec93DGkpOaxetz+dZbOQzzrBPNja7xWJSEW6FDCoGbNj0rh77HCINHaSqDIrzsWc8D06oOcP1gTnoAaK3s49Yykp5SoJYtKaLjOy4yOUcXGkpnFvJCfzR5x7mlVwtDibZY31/yzLQMXrhD4rE/0iHcaEITsytl7CxweGyH/Q6FLJtALQW5UrI44mIWH7uW45iVCfz/kqatSdHONe82YRs7bgX46Biodj+eE7qdQTQq36ndd05pzljRauH/fhQhSVSijRYMieZ/S9To+pd9qozbXPFznZCiAYWc7evuBdNpJ1houAJIPhQkCfaBA+6iZR9321ZFsReL2O+bvoxyvDffqKGr/96q5CA14H+/7G9uZh50iRO+Wl73mb5gaiiZkOOsmU1FRkbYDzu93WmxskgwSoGdqiDhPmsowuSRttH5wV/HE4UkYybCgN0c9ARSO+ipYAz8o0zN6QNB+MoCK9gKiGkQFSUnmLtI=
    bucket: twotek-revisions
    key: revision.zip
    bundle_type: zip
    application: twotek
    deployment_group: twotek-deployment-group
    region: eu-west-1
