version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/workspace/twotek
hooks:
  ApplicationStop:
   - location: scripts/stop_server.sh
     runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
